import type { MindMapNode } from '../types/mindmap'

/**
 * Stage A2 — ancestor chain lookup.
 *
 * Given a tree (forest) of MindMapNode and a target node id, return the
 * ordered list of node ids from a root down to the target (inclusive).
 *
 * Returns `[]` when the target id is not found anywhere in the tree. When
 * the target appears under multiple roots, the first DFS pre-order match
 * wins — the chain only describes one of the possible paths, but for a
 * mindmap that is generated by `mindmap-generator` the id space is unique
 * per node, so this is the right behaviour.
 *
 * Pure function. No React, no side effects. Unit-tested in
 * `src/lib/__tests__/mindmap-path.test.ts`.
 */
export function findAncestorChain(tree: MindMapNode[], nodeId: string): string[] {
  // Iterative DFS to keep this cheap on large trees. The chain is built in
  // reverse (target first) and reversed at the end so callers always get
  // root-first order.
  type Frame = { node: MindMapNode; trail: string[] }
  const stack: Frame[] = tree.map((node) => ({ node, trail: [node.id] }))

  while (stack.length > 0) {
    const frame = stack.pop()
    if (!frame) break
    const { node, trail } = frame
    if (node.id === nodeId) return trail
    for (let i = node.children.length - 1; i >= 0; i--) {
      const child = node.children[i]
      if (!child) continue
      stack.push({ node: child, trail: [...trail, child.id] })
    }
  }
  return []
}
